# Generated by Django 4.1.7 on 2023-02-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='dealership',
            new_name='super_type',
        ),
    ]
